### ISSUE TITLE
Email Integration

### ISSUE THREAD

**Issue by whosFritz** [olech2412/MensaHub#155]
Benutzer soll Email bekommen, wenn es eine Empfehlung für ihn gibt.

In Email steht dann irgendwas

**Comment by olech2412** [comment]
Funktionen:
- Wenn User nur die Empfehlungen bekommen will (Newsletter Anmeldung) erhält dieser einen Tag im voraus die Empfohlenen Gerichte (empfohlen wenn >3 und TrustScore != Niedrig) - wegen Uhrzeit keine Ahnung wie wir das machen wollen
- Ausnahmebehandlung (wenn für morgen noch keine Gerichte feststehen usw.) beachten
- Alle anderen die den normalen Newsletter abboniert haben bekommen das Rating einfach hinten dran gehängt im normalen Newsletter
