### ISSUE TITLE
Unzumutbares Verhalten bei der zeitweisen Deaktivierung des MensaHub-Newsletters

### ISSUE THREAD

**Issue by LenMPorath** [olech2412/MensaHub#93]
Unter den Newsletter-Einstellungen unter der temporären Deaktivierung ist es möglich bei dem Datepicker vergangene Daten auszuwählen. Das kann nach meiner intensiven Recherche in diesem Repository zu nicht zumutbaren und nicht vorhersehbarem Verhalten führen.
![image](https://github.com/user-attachments/assets/fcea69b3-7763-4af5-94d0-f5ab052d4146)

Außerdem soll das eine _deutsche_ Website sein! Also bitte die Datepicker-Inhalte auch auf _deutsch_ darstellen!

MfG!

**Comment by LenMPorath** [comment]
Man kann manuell das Datum eintragen. Habe ausversehen jetzt den 14.07.2024 eingegeben. Ich hoffe man kann diesen kritischen Fehler noch beheben. Ich kann mir diese überaus tollen Mensa-Angebote auf gar keinen Fall entgehen lassen!!!!

**Comment by olech2412** [comment]
feddich

**Comment by olech2412** [comment]
commit kannste selber gucken

**Comment by LenMPorath** [comment]
😮
