### ISSUE TITLE
Broken Feature: "Zum Speiseplan" führt zum Login!

### ISSUE THREAD

**Issue by LenMPorath** [olech2412/MensaHub#94]
Die Schaltfläche "Zum Speiseplan" führt mich nur zu der Anmeldeseite des MensaHub's!

![image](https://github.com/user-attachments/assets/52cd353f-adc3-4b47-a449-4b96c46750be)

Bitte fixen. Ich muss auf täglicher Basis den originalen Speiseplan der Schönauer Straße einsehen!

**Comment by olech2412** [comment]
already fixed sry

**Comment by LenMPorath** [comment]
Kann nicht sein. Die Mail die ich heute morgen erhalten habe war genau so fehlerhaft!

**Comment by olech2412** [comment]
Fixed um 08:05 siehe: https://github.com/olech2412/MensaHub/commit/534f5566bd5f0a1eda0347f3ba5e753a360a269c

**Comment by LenMPorath** [comment]
Ich wette nen Zwambo (in Cent) dass das immer noch nicht geht

**Comment by olech2412** [comment]
Ich auch
